server:
  servlet:
    context-path: /bank
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sad
    password: happy
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
